export const PERSON_LOADING = 'PERSON_LOADING'
export const PERSON_LOADED = 'PERSON_LOADED'
export const PERSON_ERROR = 'PERSON_ERROR'

export const CHANGE_INPUT_FIND = 'CHANGE_INPUT_FIND'

export const CHANGE_ACTIVE_MOBILE = 'CHANGE_ACTIVE_MOBILE'